### PR TITLE
Fix #575 FA/18-C UFC Comm triangle symbol not mapping properly

### LINKED ISSUE #575: F/A-18C: Comm triangular channel symbol ^ unavailable
**DCS-BIOS version** v0.8.0 (latest)

**DCS-BIOS Control**

`onUfcComm1DisplayChange` and `onUfcComm2DisplayChange`

**Describe the bug**

The triangle symbol that shows when the radios are turned off (?) should also be routed to the `onUfcComm*DisplayChange` handlers.

~However, it looks like [these lines](https://github.com/DCS-Skunkworks/dcs-bios/blame/7b35b54ded6d61bf4097a1ca123748b24e615ed1/Scripts/DCS-BIOS/lib/modules/aircraft_modules/FA-18C_hornet.lua#L148) replace the `^` by a `1` or `2` and after the `padLeft` the resulting message is identical to the channel strings ` 1` or ` 2`.~
Correction: the replacement is just for changing ``"`3"`` → `"13"` or `"~0"`→`"20"`. The `^` in there is just part of the RegEx.

**To Reproduce**

I don't know how to debug these messages.

**Expected behavior**

The triangle symbol should get reported as or `^` or ` ^` which is the most intuitive character for this.

Then one can show it on 16-segment displays :)

**Screenshots**

image

### PR DESCRIPTION
**Pull request by charliefoxtwo**
Fixes #575 

Unclear if this symbol is caused by receiving transmissions on the radio or something else. Would appreciate additional insight.

### CODE REVIEW

File: Scripts/DCS-BIOS/lib/modules/aircraft_modules/FA-18C_hornet.lua [hunk 1]
```diff
@@ -157,10 +161,19 @@ FA_18C_hornet:addExportHook(function()
...
 
-	return comm_channel_map[display_value] or 0
+	if display_value == "d" then -- receiving(?), comm channel hasn't changed
+		return comm_channel_cache[channel] or 0
+	end
+
+	local value = comm_channel_map[display_value] or 0
+	comm_channel_cache[channel] = value
+
+	return value
```
Comment (michaelosthege) [inline Scripts/DCS-BIOS/lib/modules/aircraft_modules/FA-18C_hornet.lua:176]: I'm new to Lua, so I may be a bit confused by the syntax here..

Why did you introduce the `comm_channel_cache`?

Comment (charliefoxtwo) [reply Scripts/DCS-BIOS/lib/modules/aircraft_modules/FA-18C_hornet.lua:176]: This was added to fix a different control that this symbol breaks, which outputs a numeric value for the channel selected. As this symbol _I assume_ is shown for all channels, we want to make sure we're still reporting that the same integer value is selected as the channel selection hasn't changed.

At least, I assume. I don't know why this control was added or who (if anyone) currently uses it.

**Comment by michaelosthege** [comment]
I tested this and it works great!

Turns out the `<>` symbol indicates incoming radio transmissions.

**Review by michaelosthege — APPROVED** [review]
